function(knix_add_system_test test_name)
    set(options QEMU BOCHS)
    set(oneValueArgs FIXTURES_SETUP FIXTURES_REQUIRED RESOURCE_LOCK WORKING_DIRECTORY DEPENDS SKIP_RETURN_CODE)
    set(multiValueArgs COMMAND LABELS)
    cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ARG_COMMAND)
        message(FATAL_ERROR "knix_add_system_test(${test_name}) requires COMMAND")
    endif()

    add_test(NAME ${test_name} COMMAND ${ARG_COMMAND})

    set(_labels integration)
    if(ARG_QEMU)
        list(APPEND _labels qemu)
    endif()
    if(ARG_BOCHS)
        list(APPEND _labels bochs)
    endif()
    if(ARG_LABELS)
        list(APPEND _labels ${ARG_LABELS})
    endif()

    set_tests_properties(${test_name} PROPERTIES LABELS "${_labels}")

    if(ARG_WORKING_DIRECTORY)
        set_tests_properties(${test_name} PROPERTIES WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}")
    endif()
    if(ARG_FIXTURES_SETUP)
        set_tests_properties(${test_name} PROPERTIES FIXTURES_SETUP "${ARG_FIXTURES_SETUP}")
    endif()
    if(ARG_FIXTURES_REQUIRED)
        set_tests_properties(${test_name} PROPERTIES FIXTURES_REQUIRED "${ARG_FIXTURES_REQUIRED}")
    endif()
    if(ARG_RESOURCE_LOCK)
        set_tests_properties(${test_name} PROPERTIES RESOURCE_LOCK "${ARG_RESOURCE_LOCK}")
    endif()
    if(ARG_DEPENDS)
        set_tests_properties(${test_name} PROPERTIES DEPENDS "${ARG_DEPENDS}")
    endif()
    if(ARG_SKIP_RETURN_CODE)
        set_tests_properties(${test_name} PROPERTIES SKIP_RETURN_CODE "${ARG_SKIP_RETURN_CODE}")
    endif()
endfunction()
